# Permalinks
permalink:        pretty

# Setup
title:            Jordan Bibla
tagline:          Product Leader
url:              https://jbib.la
paginate:         50
baseurl:          /
iconurl:          /icons/
author:
  name:           Jordan Bibla
  url:            https://jbib.la

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jolesbi/jolesbi.github.io

# Gems
gems:             [jekyll-paginate]
