# Permalinks
permalink:        pretty

# Setup
title:            Jordan Bibla
tagline:          Product Design
url:              http://jordanbibla.com
paginate:         50
baseurl:          /
iconurl:          /icons/
author:
  name:           Jordan Bibla
  url:            jordanbibla.com
  email:          jbibla@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jolesbi/jolesbi.github.io

# Gems
gems:             [jekyll-paginate]
